const questionsTema7 = {
    total: "10",
    id: "7",
    tittle: "Gestión de Errores y Excepciones",
    information: "La gestión de errores y excepciones es un aspecto crucial en el desarrollo de software que permite manejar situaciones inesperadas y garantizar la robustez y fiabilidad de un programa. Comprender cómo identificar, lanzar y manejar errores y excepciones es esencial para escribir código sólido y evitar fallas inesperadas.",
    questions: [
        {
            id: "1",
            answers_tittle: "¿Qué es un error en programación?",
            answers: {
                a: "Un problema que se produce cuando el código no se ejecuta correctamente",
                b: "Un valor que representa un resultado no válido en una operación matemática",
                c: "Un tipo de dato que indica la ausencia de un valor"
            },
            correctAnswer: "inciso a"
        },
        {
            id: "2",
            answers_tittle: "¿Qué es una excepción en programación?",
            answers: {
                a: "Un problema que se produce cuando el código no se ejecuta correctamente",
                b: "Un valor que representa un resultado no válido en una operación matemática",
                c: "Un tipo de dato que indica la ausencia de un valor"
            },
            correctAnswer: "inciso a"
        },
        {
            id: "3",
            answers_tittle: "¿Qué se utiliza para identificar y manejar errores en JavaScript?",
            answers: {
                a: "La declaración try-catch",
                b: "La declaración if-else",
                c: "La declaración for"
            },
            correctAnswer: "inciso a"
        },
        {
            id: "4",
            answers_tittle: "¿Qué se utiliza para lanzar una excepción en JavaScript?",
            answers: {
                a: "La declaración throw",
                b: "La declaración catch",
                c: "La declaración finally"
            },
            correctAnswer: "inciso a"
        },
        {
            id: "5",
            answers_tittle: "¿Qué es el bloque catch en JavaScript?",
            answers: {
                a: "El bloque que se ejecuta después del bloque try si no se produce ninguna excepción",
                b: "El bloque que se ejecuta cuando se produce una excepción en el bloque try",
                c: "El bloque que se ejecuta después del bloque try, independientemente de si se produce una excepción o no"
            },
            correctAnswer: "inciso b"
        },
        {
            id: "6",
            answers_tittle: "¿Cuál es el propósito del bloque finally en JavaScript?",
            answers: {
                a: "El bloque que se ejecuta después del bloque try si no se produce ninguna excepción",
                b: "El bloque que se ejecuta cuando se produce una excepción en el bloque try",
                c: "El bloque que se ejecuta después del bloque try, independientemente de si se produce una excepción o no"
            },
            correctAnswer: "inciso c"
        },
        {
            id: "7",
            answers_tittle: "¿Qué es el objeto Error en JavaScript?",
            answers: {
                a: "Un objeto que representa un error en tiempo de ejecución",
                b: "Un objeto que representa una excepción lanzada por el programador",
                c: "Un objeto que representa una excepción lanzada por el sistema"
            },
            correctAnswer: "inciso a"
        },
        {
            id: "8",
            answers_tittle: "¿Qué método se utiliza para imprimir el mensaje de error asociado a una excepción en JavaScript?",
            answers: {
                a: "message()",
                b: "getMessage()",
                c: "toString()"
            },
            correctAnswer: "inciso a"
        },
        {
            id: "9",
            answers_tittle: "¿Qué es la propagación de errores en JavaScript?",
            answers: {
                a: "El proceso de manejar un error antes de que se propague a otros bloques de código",
                b: "El proceso de pasar un error de una función a otra hasta que se maneje",
                c: "El proceso de crear múltiples excepciones a partir de un solo error"
            },
            correctAnswer: "inciso b"
        },
        {
            id: "10",
            answers_tittle: "¿Qué es el bloque try en JavaScript?",
            answers: {
                a: "El bloque que se ejecuta después del bloque catch si se produce una excepción",
                b: "El bloque que se ejecuta cuando se produce una excepción en el código",
                c: "El bloque en el que se coloca el código que podría producir una excepción"
            },
            correctAnswer: "inciso c"
        }
    ]
}

export default questionsTema7;
